add_lunch_combo hyperion_d2lte-userdebug
add_lunch_combo hyperion_d2vzw-userdebug
add_lunch_combo hyperion_jflte-userdebug
add_lunch_combo hyperion_i605-userdebug
add_lunch_combo hyperion_vanquish-userdebug
add_lunch_combo hyperion_p3110-userdebug

